server:
  port: 8764
spring:
  application:
    name: service-ribbon
eureka:
  client:
    serviceUrl:
      registryFetchIntervalSeconds: 5
      defaultZone: http://192.168.1.9:8761/eureka/
  instance:
    leaseRenewalIntervalInSeconds: 10