#spring.application.name=config-client
#spring.cloud.config.label=master
#spring.cloud.config.profile=dev
#spring.cloud.config.uri= http://localhost:8888/
#server.port=8881
spring:
  cloud:
    config:
      label: master
      profile: dev
      uri: http://localhost:8888/
  application:
    name: config-client
server:
  port: 8881